# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import textbooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0022_auto_20151101_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=200, verbose_name='Авторы')),
                ('is_compiler', models.BooleanField(default=False, verbose_name='Составитель?')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('year', models.IntegerField(blank=True, null=True, validators=[[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2100)]], verbose_name='Год издания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('course', models.ManyToManyField(blank=True, null=True, to='courses.Course', verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'пособие',
                'verbose_name_plural': 'пособия',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TextbookFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to=textbooks.models.upload_textbook_files_to, verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.Textbook', verbose_name='Пособие')),
            ],
            options={
                'verbose_name': 'материалы пособия',
                'verbose_name_plural': 'материалы пособия',
                'ordering': ['textbook', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='textbookfile',
            unique_together=set([('textbook', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='textbook',
            unique_together=set([('title',)]),
        ),
    ]
