# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Курсы'),
        ),
    ]
