# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_auto_20151227_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='course',
            new_name='courses',
        ),
    ]
