# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0004_auto_20160102_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookfile',
            options={'ordering': ['textbook', 'order', 'title'], 'verbose_name': 'материалы пособия', 'verbose_name_plural': 'материалы пособия'},
        ),
    ]
